---
- name: Restart Samba and Avahi
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - "{{ 'smbd' if ansible_facts['os_family'] == 'Debian' else 'smb' }}"
    - "{{ 'nmbd' if ansible_facts['os_family'] == 'Debian' else 'nmb' }}"
    - avahi-daemon
