all:
  children:
    dns_servers:
      hosts:
        adguard:
          ansible_host: 192.168.1.21
    reverse_proxies:
      hosts:
        nginx:
          ansible_host: 192.168.1.22
    proxmox_nodes:
      hosts:
        pve:
          ansible_host: 192.168.1.20
