all:
  children:
    core_network:
      hosts:
        adguard:
          ansible_host: 192.168.1.21
        nginx:
          ansible_host: 192.168.1.22
    iot:
      hosts:
        homeassistant:
          ansible_host: 192.168.1.24
    media:
      hosts:
        jellyfin:
          ansible_host: 192.168.1.25
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
