---
pihole_interface: "eth0"
pihole_dns_listening_mode: "single"
pihole_upstream_dns:
  - "1.1.1.1"
  - "1.0.0.1"

pihole_custom_records:
  - ip: "192.168.1.22"
    domain: "agh.home"
  - ip: "192.168.1.22"
    domain: "hass.home"
  - ip: "192.168.1.22"
    domain: "jellyfin.home"
  - ip: "192.168.1.22"
    domain: "deluge.home"
  - ip: "192.168.1.22"
    domain: "prowlarr.home"
  - ip: "192.168.1.22"
    domain: "radarr.home"
  - ip: "192.168.1.22"
    domain: "sonarr.home"
  - ip: "192.168.1.22"
    domain: "flaresolverr.home"
