---
- name: Deploy Pure NGINX Ingress Router
  hosts: reverse_proxies
  gather_facts: yes
  vars:
    nginx_virtual_hosts:
      - domain: agh.lan
        upstream: http://192.168.1.21:8083
  roles:
    - nginx
