---
- name: Deploy and Configure Ingress NGINX Router
  hosts: nginx
  become: true
  vars:
    nginx_virtual_hosts:
      - domain: agh.home
        upstream: http://192.168.1.21:8083
      - domain: hass.home
        upstream: http://192.168.1.24:8123
      - domain: jellyfin.home
        upstream: http://192.168.1.25:8096
      - domain: deluge.home
        upstream: http://192.168.1.26:8112
  roles:
    - nginx
