---
- name: Deploy Declarative Apple Samba Server on PVE Host
  hosts: pve
  vars_prompt:
    - name: samba_password
      prompt: "Enter desired SMB password for adminx (for iPhone/iPad/Mac)"
      private: yes
      confirm: yes
  vars:
    samba_user: adminx
  roles:
    - samba_server
